import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'inicio',
        path: '/home',
        title: 'Inicio',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'resume',
        path: '',
        title: 'Resumen',
        translateKey: 'nav.groupMenu.resume',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'resume.projects',
                path: '/analytics/projects-panel',
                title: 'Proyectos',
                translateKey: 'nav.resume.projects',
                icon: 'projectMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'resume.reports',
                path: '/analytics/hh-reports',
                title: 'Reportes HH',
                translateKey: 'nav.groupMenu.reports',
                icon: 'hhMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'backOffice',
        path: '',
        title: 'Back Office',
        translateKey: 'nav.groupMenu.backOffice',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'backOffice.certifications',
                path: '/backoffice?section=certifications',
                title: 'Certificaciones',
                translateKey: 'nav.backOffice.certifications',
                icon: 'certificateMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'backOffice.roles',
                path: '/backoffice?section=roles',
                title: 'Cargos',
                translateKey: 'nav.backOffice.roles',
                icon: 'rolesMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'backOffice.clients',
                path: '/backoffice?section=clients',
                title: 'Clientes',
                translateKey: 'nav.backOffice.clients',
                icon: 'clientsMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'backOffice.holidays',
                path: '/backoffice?section=holidays',
                title: 'Feriados',
                translateKey: 'nav.backOffice.holidays',
                icon: 'holidaysMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'backOffice.chores',
                path: '/backoffice?section=chores',
                title: 'Faenas',
                translateKey: 'nav.backOffice.chores',
                icon: 'choreMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'backOffice.divisions',
                path: '/backoffice?section=divisions',
                title: 'Divisiones',
                translateKey: 'nav.backOffice.divisions',
                icon: 'divisionMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'backOffice.shifts',
                path: '/backoffice?section=shifts',
                title: 'Turnos',
                translateKey: 'nav.backOffice.shifts',
                icon: 'shiftMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'p&c',
        path: '',
        title: 'P&C',
        translateKey: 'nav.groupMenu.p&c',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'p&c.matrix',
                path: '/certifications',
                title: 'Matrices de Certificaciones',
                translateKey: 'nav.p&c.matrix',
                icon: 'certificateMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'p&c.contributors',
                path: '/collaborators',
                title: 'Colaboradores',
                translateKey: 'nav.p&c.contributors',
                icon: 'collabsMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'projects',
        path: '',
        title: 'Proyectos',
        translateKey: 'nav.groupMenu.projects',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'projects.services',
                path: '/services',
                title: 'Servicios',
                translateKey: 'nav.projects.services',
                icon: 'servicesMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'admin',
        path: '',
        title: 'Admin',
        translateKey: 'nav.groupMenu.admin',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'admin.rolesUsers',
                path: '/roles-users',
                title: 'Roles y Usuarios',
                translateKey: 'nav.admin.rolesUsers',
                icon: 'usersMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
